spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

  security:
    user:
      name: drones
      password: "%$Drones123!@#"

drones-app:
  file-storage:
    directory: ./drones-app
    file-types: .jpg,.png,.csv,.jpeg,.bpm,.wbmp,.gif